//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class activity
    {
        public long id { get; set; }
        public Nullable<long> id_event { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string name { get; set; }
        public Nullable<int> day { get; set; }
        public Nullable<System.TimeSpan> time { get; set; }
    }
}
