//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class country
    {
        public long id { get; set; }
        public string name { get; set; }
        public string eng_name { get; set; }
        public string code { get; set; }
        public Nullable<int> code_2 { get; set; }
    }
}
