//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class @event
    {
        public long id { get; set; }
        public string name { get; set; }
        public string date { get; set; }
        public Nullable<int> days { get; set; }
        public Nullable<int> city { get; set; }
    }
}
