//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class moderator
    {
        public long id { get; set; }
        public string name { get; set; }
        public string sex { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> date_of_birth { get; set; }
        public Nullable<int> country { get; set; }
        public string number { get; set; }
        public string direction { get; set; }
        public string @event { get; set; }
        public string password { get; set; }
        public string photo { get; set; }
    }
}
